apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2023-10-13T17:09:53Z"
  generation: 1
  name: my-flask-app
  namespace: default
  resourceVersion: "4611"
  uid: 243c19b8-3f6d-48af-88f0-048146d6977c
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: my-flask-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-flask-app
    spec:
      containers:
      - image: 098443230348.dkr.ecr.us-east-1.amazonaws.com/cloud-native-monitoring-app:latest
        imagePullPolicy: Always
        name: my-flask-container
        ports:
        - containerPort: 5000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-10-13T17:09:54Z"
    lastUpdateTime: "2023-10-13T17:09:54Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2023-10-13T17:09:53Z"
    lastUpdateTime: "2023-10-13T17:09:54Z"
    message: ReplicaSet "my-flask-app-58fb78dd99" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
