
      
name: Build and push react image to ECR

on:
  push:
    branches: ["master"]   
  

jobs:
  
  build:
    
    name: Build Image
    runs-on: ubuntu-latest

   
    steps:

    - name: Check out code
      uses: actions/checkout@v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Login to Amazon ECR
    
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
    
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: cloud-native-monitoring-app
        IMAGE_TAG: ${{ github.sha }}
        
      run: |
      
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        
  update-manifest:
  
    runs-on: ubuntu-latest 
    
    needs: ['build']
    
    steps:
    
      - uses: actions/checkout@v3
        with: 
        
          ref: 'kubernetes'
          token: ${{ secrets.G_TOKEN }}
          
      - name: setup git config
      
        run: |
          git config --global user.email "chiragdksh@gmail.com"
          git config --global user.name "vikashkumar0712"
          echo ${{ github.sha }}
          sed -i 's+098443230348.dkr.ecr.us-west-2.amazonaws.com/cloud-native-monitoring-app:.*+098443230348.dkr.ecr.us-east-2.amazonaws.com/cloud-native-monitoring-app:${{ github.sha }}+g' deployment.yaml
          git add -A
          git commit -m "Update image for - ${{ github.sha }}"
          
      - run: echo ${{ github }}
      - run: git push -u origin master
